---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: rricky25/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
#    - name: Check if "calculator" container exists
#      docker_container:
#        name: calculator
#        state: absent
#        register: container_check
    - name: Running container
      shell: docker run -it -d --name Calculator rricky25/calculator