---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Pull image
      docker_image:
        name: rricky25/calculator:latest
        source: pull
    - name: Check if "calculator" container exists
      docker_container:
        name: Calculator
        state: absent
    - name: Running container
      shell: docker run -it -d --name Calculator rricky25/calculator